spring:
  profiles: yang
    active:
    - dev
---
spring:
  profiles: dev          #开发环境
  application:
    name: yang-dev
---
spring:
  profiles: test          #测试环境
  application:
    name: yang-test
